name: Cypress tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        browser: ['chrome', 'firefox']
    name: Run Cypress tests on ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          headed: true
          browser: ${{ matrix.browser }}
          env: BROWSER=${{ matrix.browser }}
          record: false
          command: npm run test:cypress
